#==============================================================================
# minimal nginx
#==============================================================================
FROM oddpoet/alpine-base:latest
MAINTAINER yunsang.choi<oddpoet@gmail.com>


# install nginx
ENV NGINX_VERSION   "1.10.3-r0"
RUN apk --update add "nginx=${NGINX_VERSION}"
